# 正式环境配置
app:
  environment: pro

server:
  port: 8083
  # 开启优雅停机
  shutdown: graceful
  servlet:
    context-path: /spba

spring:
  lifecycle:
    # 设置缓冲期，最大等待时间
    timeout-per-shutdown-phase: 15s
  servlet:
    multipart:
      max-file-size: 2MB      # 单个文件大小
      max-request-size: 10MB  # 总上传的数据大小
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spba?serverTimezone=UTC&useUniode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: abc123456
    initial-size: 2
    max-active: 20
    min-idle: 0
    max-wait: 60000
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    pool-prepared-statements: false
  # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 300
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0

# mybatis-plus配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.spba.api.domain
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: false

#logging:
#  config: classpath:log.xml

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 900
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

spba:
  ip:
  domain-name:
  storage-url:
  qiniu:
    bucket-name:
    access-key:
    secret-key: